"""initial migration

Revision ID: b34e49f57bdb
Revises: 
Create Date: 2024-12-31 00:43:18.897556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34e49f57bdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chess_players',
    sa.Column('chess_player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('world_rank', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('chess_player_id', 'id')
    )
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('tournament_id', 'id')
    )
    op.create_table('participants',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('chess_player_id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['chess_player_id'], ['chess_players.chess_player_id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'id'),
    sa.UniqueConstraint('participant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('tournaments')
    op.drop_table('chess_players')
    # ### end Alembic commands ###
